export const esAR = {
  locale: 'es-AR',
  socialButtonsBlockButton: 'Continuar con {{provider|titleize}}',
  socialButtonsBlockButtonManyInView: '{{provider|titleize}}',
  dividerText: 'o',
  formFieldLabel__emailAddress: 'Email',
  formFieldLabel__password: 'Contraseña',
  formFieldLabel__firstName: 'Nombre',
  formFieldLabel__lastName: 'Apellido',
  formFieldLabel__username: 'Nombre de usuario',
  formFieldLabel__phoneNumber: 'Teléfono',
  formButtonPrimary: 'Continuar',
  formButtonPrimary__signIn: 'Ingresar',
  formButtonPrimary__signUp: 'Crear cuenta',
  formButtonPrimary__verify: 'Verificar',
  formFieldError__notMatchPasswords: 'Las contraseñas no coinciden',
  formFieldError__minLength: 'Mínimo {{length}} caracteres',

  signIn: {
    start: {
      title: 'Ingresá a Inmersivapp',
      subtitle: 'Ingresá tu email para recibir un código',
      emailPlaceholder: 'tu@email.com',
      buttonText: 'Continuar',
      dividerText: 'o',
      actionText: '¿No tenés cuenta?',
      actionLink: 'Registrate',
      actionLink__use_email: 'Usar email',
      actionLink__use_phone: 'Usar teléfono',
      actionLink__use_username: 'Usar nombre de usuario',
      actionLink__use_passkey: 'Usar clave de acceso',
      actionLink__use_email_username: 'Usar email o usuario',
      actionLink__join_waitlist: 'Unite a la lista de espera',
      actionText__join_waitlist: '¿Querés unirte a la lista de espera?',
      subtitleCombined: undefined,
      titleCombined: undefined,
      alternativePhoneCodeProvider: {
        actionLink: undefined,
        label: undefined,
        subtitle: undefined,
        title: undefined,
      },
    },
    password: {
      title: 'Ingresá tu contraseña',
      subtitle: 'Usá tu email y contraseña para iniciar sesión',
      emailPlaceholder: 'tu@email.com',
      passwordPlaceholder: '••••••••',
      buttonText: 'Ingresar',
      forgotPasswordLinkText: '¿Olvidaste tu contraseña?',
      forgotPasswordLinkTextMobile: 'Olvidé mi contraseña',
    },
    forgotPassword: {
      title: 'Recuperar contraseña',
      subtitle: 'Te enviamos un código a tu email',
      emailPlaceholder: 'tu@email.com',
      buttonText: 'Enviar código',
    },
    resetPassword: {
      title: 'Nueva contraseña',
      subtitle: 'Ingresá tu nueva contraseña',
      newPasswordPlaceholder: 'Nueva contraseña',
      confirmPasswordPlaceholder: 'Confirmar contraseña',
      buttonText: 'Cambiar contraseña',
    },
    backupCodeMfa: {
      title: 'Introducí un código de seguridad',
      subtitle: 'para continuar a {{applicationName}}',
    },
    emailCode: {
      title: 'Revisá tu email',
      subtitle: 'para continuar a {{applicationName}}',
      formTitle: 'Código de verificación',
      resendButton: 'Reenviar código',
    },
    emailLink: {
      title: 'Revisá tu email',
      subtitle: 'para continuar a {{applicationName}}',
      formTitle: 'Enlace de verificación',
      formSubtitle: 'Usá el enlace de verificación enviado a tu email',
      resendButton: 'Reenviar enlace',
      expired: {
        title: 'Este enlace de verificación expiró',
        subtitle: 'Volvé a la pestaña original para continuar.',
      },
      failed: {
        title: 'Este enlace de verificación es inválido',
        subtitle: 'Volvé a la pestaña original para continuar.',
      },
      loading: {
        title: 'Iniciando sesión...',
        subtitle: 'Vas a ser redirigido pronto',
      },
      verified: {
        title: 'Verificado con éxito',
      },
      verifiedSwitchTab: {
        title: 'Email verificado con éxito',
        subtitle: 'Volvé a la pestaña recién abierta para continuar',
        subtitleNewTab: 'Volvé a la pestaña anterior para continuar',
      },
      clientMismatch: {
        title: 'Error de dispositivo',
        subtitle: 'Parece que no estás usando el dispositivo correcto para verificar.',
      },
    },
    phoneCode: {
      title: 'Revisá tu teléfono',
      subtitle: 'para continuar a {{applicationName}}',
      formTitle: 'Código de verificación',
      resendButton: 'Reenviar código',
    },
    totpMfa: {
      title: 'Verificación de dos pasos',
      subtitle: 'Introducí el código de tu aplicación de autenticación',
      formTitle: 'Código de verificación',
    },
    alternativeMethods: {
      title: 'Usá otro método',
      subtitle: '¿Tenés problemas? Podés usar cualquiera de estos métodos.',
      actionText: '¿No tenés ninguno de estos?',
      actionLink: 'Conseguí ayuda',
      blockButton__password: 'Ingresá con tu contraseña',
      blockButton__emailCode: 'Enviar código a {{identifier}}',
      blockButton__emailLink: 'Enviar enlace a {{identifier}}',
      blockButton__phoneCode: 'Enviar código a {{identifier}}',
      blockButton__totp: 'Usá tu app de autenticación',
      blockButton__backupCode: 'Usá un código de respaldo',
      blockButton__passkey: 'Usá clave de acceso',
      getHelp: {
        title: 'Conseguí ayuda',
        content: 'Si tenés problemas para iniciar sesión, envianos un email y te ayudamos.',
        blockButton__emailSupport: 'Soporte por email',
      },
    },
    accountSwitcher: {
      title: 'Elegí una cuenta',
      subtitle: 'Seleccioná la cuenta con la que querés continuar.',
      action__addAccount: 'Agregar cuenta',
      action__signOutAll: 'Cerrar sesión de todas las cuentas',
    },
  },
  signUp: {
    start: {
      title: 'Creá tu cuenta',
      subtitle: 'Completá tus datos para registrarte',
      emailPlaceholder: 'tu@email.com',
      passwordPlaceholder: 'Crear contraseña',
      confirmPasswordPlaceholder: 'Confirmar contraseña',
      buttonText: 'Crear cuenta',
      dividerText: 'o',
      actionText: '¿Ya tenés una cuenta?',
      actionLink: 'Iniciar sesión',
      actionLink__use_email: 'Usar email',
      actionLink__use_phone: 'Usar teléfono',
      subtitleCombined: 'para continuar en {{applicationName}}',
      titleCombined: 'Creá tu cuenta',
      alternativePhoneCodeProvider: {
        actionLink: undefined,
        label: undefined,
        subtitle: undefined,
        title: undefined,
      },
    },
    continue: {
      title: 'Completá los campos que faltan',
      subtitle: 'para continuar a {{applicationName}}',
      actionText: '¿Ya tenés una cuenta?',
      actionLink: 'Ingresar',
    },
    emailCode: {
      title: 'Verificá tu email',
      subtitle: 'para continuar a {{applicationName}}',
      formTitle: 'Código de verificación',
      formSubtitle: 'Introducí el código enviado a tu email',
      resendButton: 'Reenviar código',
    },
    emailLink: {
      title: 'Verificá tu email',
      subtitle: 'para continuar a {{applicationName}}',
      formTitle: 'Enlace de verificación',
      formSubtitle: 'Usá el enlace de verificación enviado a tu email',
      resendButton: 'Reenviar enlace',
      loading: {
        title: 'Registrando...',
      },
      verified: {
        title: 'Registrado con éxito',
      },
      verifiedSwitchTab: {
        title: 'Email verificado con éxito',
        subtitle: 'Volvé a la pestaña recién abierta para continuar',
        subtitleNewTab: 'Volvé a la pestaña anterior para continuar',
      },
      clientMismatch: {
        title: 'Error de dispositivo',
        subtitle: 'Parece que no estás usando el dispositivo correcto para verificar.',
      },
    },
    phoneCode: {
      title: 'Verificá tu teléfono',
      subtitle: 'para continuar a {{applicationName}}',
      formTitle: 'Código de verificación',
      formSubtitle: 'Introducí el código enviado a tu teléfono',
      resendButton: 'Reenviar código',
    },
  },
  userButton: {
    action__signOut: 'Cerrar sesión',
    action__manageAccount: 'Administrar cuenta',
    action__signOutAll: 'Cerrar sesión en todos los dispositivos',
  },
  otp: {
    label: 'Código de verificación',
    buttonText: 'Verificar',
    resendButton: 'Reenviar código',
  },
  footerActionLink__signIn: '¿Ya tenés cuenta? Ingresá',
  footerActionLink__signUp: '¿No tenés cuenta? Registrate',
  footerPageLink__help: 'Ayuda',
  footerPageLink__privacy: 'Privacidad',
  footerPageLink__terms: 'Términos',
  footerActionLink__useAnotherMethod: 'Usar otro método',
  backLink: 'Volver',
  formFieldLabel__organizationName: 'Nombre de la organización',
  formFieldLabel__organizationSlug: 'Identificador',
  formFieldInputPlaceholder__organizationName: 'Mi Organización',
  formFieldInputPlaceholder__organizationSlug: 'mi-organizacion',

  // English defaults for Clerk internal components
  badge__thisDevice: 'Este dispositivo',
  badge__userDevice: 'Dispositivo de usuario',
  badge__unverified: 'No verificado',
  badge__primary: 'Principal',
  badge__requiresAction: 'Requiere acción',
  badge__you: 'Vos',
}