export const esAR = {
  locale: 'es-AR',
  signIn: {
    start: {
      title: 'Ingresá a Inmersivapp',
      subtitle: 'Ingresá tu email para recibir un código',
      emailPlaceholder: 'tu@email.com',
      buttonText: 'Continuar',
      dividerText: 'o',
    },
    password: {
      title: 'Ingresá tu contraseña',
      subtitle: 'Usá tu email y contraseña para iniciar sesión',
      emailPlaceholder: 'tu@email.com',
      passwordPlaceholder: '••••••••',
      buttonText: 'Ingresar',
      forgotPasswordLinkText: '¿Olvidaste tu contraseña?',
      forgotPasswordLinkTextMobile: 'Olvidé mi contraseña',
    },
    forgotPassword: {
      title: 'Recuperar contraseña',
      subtitle: 'Te enviamos un código a tu email',
      emailPlaceholder: 'tu@email.com',
      buttonText: 'Enviar código',
    },
    resetPassword: {
      title: 'Nueva contraseña',
      subtitle: 'Ingresá tu nueva contraseña',
      newPasswordPlaceholder: 'Nueva contraseña',
      confirmPasswordPlaceholder: 'Confirmar contraseña',
      buttonText: 'Cambiar contraseña',
    },
    socialButtonsBlockButton: 'Continuar con {{provider|titleize}}',
    dividerText: 'o',
    backLink: 'Volver',
  },
  signUp: {
    start: {
      title: 'Creá tu cuenta',
      subtitle: 'Completá tus datos para registrarte',
      emailPlaceholder: 'tu@email.com',
      passwordPlaceholder: 'Crear contraseña',
      confirmPasswordPlaceholder: 'Confirmar contraseña',
      buttonText: 'Crear cuenta',
      dividerText: 'o',
    },
    socialButtonsBlockButton: 'Registrarse con {{provider|titleize}}',
    dividerText: 'o',
    backLink: 'Ya tengo cuenta',
  },
  userButton: {
    action__signOut: 'Cerrar sesión',
    action__manageAccount: 'Administrar cuenta',
    action__signOutAll: 'Cerrar sesión en todos los dispositivos',
  },
  formFieldLabel__emailAddress: 'Email',
  formFieldLabel__password: 'Contraseña',
  formFieldLabel__firstName: 'Nombre',
  formFieldLabel__lastName: 'Apellido',
  formFieldLabel__username: 'Nombre de usuario',
  formFieldLabel__phoneNumber: 'Teléfono',
  formButtonPrimary: 'Continuar',
  formButtonPrimary__signIn: 'Ingresar',
  formButtonPrimary__signUp: 'Crear cuenta',
  footerActionLink__signIn: '¿Ya tenés cuenta? Ingresá',
  footerActionLink__signUp: '¿No tenés cuenta? Registrate',
  formFieldError__notMatchPasswords: 'Las contraseñas no coinciden',
  formFieldError__minLength: 'Mínimo {{length}} caracteres',
  otp: {
    label: 'Código de verificación',
    buttonText: 'Verificar',
    resendButton: 'Reenviar código',
  },
}